apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommendation-deployment
  labels:
    run: recommendation-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: vedatekiz/recommendation
        ports:
        - containerPort: 2222
          protocol: TCP     